### ISSUE TITLE
AIG extras screenshots 

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_AIG#1]
SILVER

![image](https://cloud.githubusercontent.com/assets/9828657/14573159/e809d86e-0318-11e6-8c95-876c27c054b5.png)

GOLD

![image](https://cloud.githubusercontent.com/assets/9828657/14573163/f28ac01e-0318-11e6-81f7-700b3038cd28.png)

PLATINUM

![image](https://cloud.githubusercontent.com/assets/9828657/14573167/fdfdc8ba-0318-11e6-8c7f-2bdaba376472.png)

**Comment by jaylindsey** [comment]
This is resolved
