### ISSUE TITLE
Mockup of select page boxes

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_AIG#3]
Jay - a mockup of the select page. I'm guessing the dimensions are about similar. 

Not set in stone - so lets talk it through again before you start implementing. 

![image](https://cloud.githubusercontent.com/assets/9828657/14621975/661af34e-058c-11e6-808f-799da20255e2.png)

**Comment by jaylindsey** [comment]
This is resolved

**Comment by stevepablow** [comment]
done closed
