### ISSUE TITLE
AIG comparison page inclusions and extra info

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_AIG#4]
Jay

I have them all in here now (attached) - though I will re-arrange the order slightly - so we can better group matching features with each other. 

[AIG-Quote-Page-Spec-V1.xlsx](https://github.com/TurkerKucuk/Pablow_AIG/files/230377/AIG-Quote-Page-Spec-V1.xlsx)

**Comment by jaylindsey** [comment]
We are good on this.
