### ISSUE TITLE
add IMG logo to each page

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_AIG#5]
![logoimg](https://cloud.githubusercontent.com/assets/9828657/14722198/003f28ce-07d0-11e6-8dd2-c0313c66c69b.PNG)

add it just above the Pablow logo

![image](https://cloud.githubusercontent.com/assets/9828657/14722289/770f082a-07d0-11e6-9c7f-d377122393bd.png)

**Comment by jaylindsey** [comment]
This is resolved and up on staging.

**Comment by jaylindsey** [comment]
They got switched oops.

**Comment by jaylindsey** [comment]
This is now resolved on staging.  On production they are flip-flopped but I will unload to prod again at the end of the day.
