### ISSUE TITLE
switch buy button to red

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_AIG#6]
Jay I reckon given we have the next button as orange - that we also have the Buy Policy button as orange. And keep Change and Back as dark colour. 

What do you reckon?

![image](https://cloud.githubusercontent.com/assets/9828657/14906088/3b864d56-0d7d-11e6-8f4e-5b121dfd7fee.png)

**Comment by jaylindsey** [comment]
This is done.  Its up on asynctestinginnovo.azurewebsites.net/Select

Homepage start is also uploaded at: asynctestinginnovo.azurewebsites.net/Home

**Comment by stevepablow** [comment]
(in due course) can you make the change page Next button red too. tx

![image](https://cloud.githubusercontent.com/assets/9828657/15048050/4dc644be-12ad-11e6-971e-8dc9b422bcdb.png)

**Comment by jaylindsey** [comment]
This is resolved and up on testing

**Comment by stevepablow** [comment]
checked - ok
